### ISSUE TITLE
Vulnerabilities in obiba/rock:1.0 image

### ISSUE THREAD

**Issue by RonanMorgan** [obiba/docker-rock#4]
Hello,

According to the "docker scout cves" API there are 6 critical vulnerability in the obiba/rock:1.0 image,

Do you know if any patches will be provided soon ?

Regards,

**Comment by ymarcon** [comment]
Could you share this report? that would help with fixing the issue.

**Comment by ymarcon** [comment]
Please use the email address dev@obiba.org to send this security report.
